language:
  - ruby

rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.5"
  - "2.2.0"

env:
  matrix:
    - "DB=mysql DB_CONN_STRING=mysql2://root@localhost/travis_ci_test"
    - "DB=postgresql DB_CONN_STRING=postgres://postgres@localhost/travis_ci_test"
    - "DB=sqlite3"

install:
  - test/prepare_travis_env.sh

script:
  - bundle exec rake test
